const studentDiscounts = [
    { id: 1, domain: 'nike.com', name: 'Nike', offer: '10% off for students', link: 'https://www.nike.com/help/a/student-discount', category: 'Fashion', code: 'STUDENT10' },
    { id: 2, domain: 'apple.com', name: 'Apple', offer: 'Education pricing on Macs', link: 'https://www.apple.com/us-edu/store', category: 'Tech' },
    { id: 3, domain: 'spotify.com', name: 'Spotify', offer: 'Premium + Hulu for $5.99/mo', link: 'https://www.spotify.com/us/student/', category: 'Entertainment' },
    { id: 4, domain: 'amazon.com', name: 'Amazon', offer: 'Prime Student 6 months free', link: 'https://www.amazon.com/student', category: 'General' },
    { id: 5, domain: 'adobe.com', name: 'Adobe', offer: '60% off Creative Cloud', link: 'https://www.adobe.com/creativecloud/buy/students.html', category: 'Tech' },
    { id: 6, domain: 'samsung.com', name: 'Samsung', offer: 'Up to 30% off', link: 'https://www.samsung.com/us/shop/discount-program/education/', category: 'Tech' },
    { id: 7, domain: 'asos.com', name: 'ASOS', offer: '10% Student Discount', link: 'https://www.asos.com/us/discover/students/asos-on-campus/student-discount/', category: 'Fashion', code: 'ASOSSTUDENT' },
    { id: 8, domain: 'levis.com', name: "Levi's", offer: '15% off + Free Shipping', link: 'https://www.levi.com/US/en_US/student-discount', category: 'Fashion' },
    { id: 9, domain: 'microsoft.com', name: 'Microsoft', offer: 'up to 10% off Surface', link: 'https://www.microsoft.com/en-us/store/b/education', category: 'Tech' },
    { id: 10, domain: 'bestbuy.com', name: 'Best Buy', offer: 'Student Deals on Tech', link: 'https://www.bestbuy.com/site/back-to-school/student-deals/pcmcat1652458421867.c', category: 'Tech' },
    { id: 11, domain: 'hulu.com', name: 'Hulu', offer: 'Student Plan $1.99/mo', link: 'https://www.hulu.com/student', category: 'Entertainment' },
    { id: 12, domain: 'youtube.com', name: 'YouTube', offer: 'Premium Student Membership', link: 'https://www.youtube.com/premium/student', category: 'Entertainment' },
    { id: 13, domain: 'dominos.com', name: "Domino's", offer: '35% off Student Discount', link: 'https://www.dominos.co.uk/blog/student-discount/', category: 'Food' },
    { id: 14, domain: 'dell.com', name: 'Dell', offer: 'Extra 5-10% off laptops', link: 'https://www.dell.com/en-us/lp/students', category: 'Tech' },
    { id: 15, domain: 'github.com', name: 'GitHub', offer: 'Free Student Developer Pack', link: 'https://education.github.com/pack', category: 'Free' },
    { id: 16, domain: 'canva.com', name: 'Canva', offer: 'Free Canva for Education', link: 'https://www.canva.com/education/', category: 'Free' },
    { id: 17, domain: 'autodesk.com', name: 'Autodesk', offer: 'Free Software for Students', link: 'https://www.autodesk.com/education/edu-software/overview', category: 'Free' },
    { id: 18, domain: 'notion.so', name: 'Notion', offer: 'Free Plus Plan for Students', link: 'https://www.notion.so/product/notion-for-education', category: 'Free' },
    { id: 19, domain: 'figma.com', name: 'Figma', offer: 'Free Professional Plan', link: 'https://www.figma.com/education/', category: 'Free' },
    { id: 20, domain: 'jet定期.com', name: 'JetBrains', offer: 'Free IDEs for students', link: 'https://www.jetbrains.com/community/education/#students', category: 'Free' },
    { id: 21, domain: 'tableau.com', name: 'Tableau', offer: 'Free 1-year Desktop license', link: 'https://www.tableau.com/academic/students', category: 'Free' },
    { id: 22, domain: 'azure.microsoft.com', name: 'Azure', offer: 'Free $100 Credit + No Credit Card', link: 'https://azure.microsoft.com/en-us/free/students/', category: 'Free' },
    { id: 23, domain: 'amtrak.com', name: 'Amtrak', offer: '15% off train travel', link: 'https://www.amtrak.com/student-discounts', category: 'Travel' },
    { id: 24, domain: 'statravel.com', name: 'STA Travel', offer: 'Exclusive student flights', link: 'https://www.statravel.com/', category: 'Travel' },
    { id: 25, domain: 'uber.com', name: 'Uber Eats', offer: 'Student discount on orders', link: 'https://www.ubereats.com/', category: 'Food' },
    { id: 26, domain: 'unidays.com', name: 'UNiDAYS', offer: 'Massive portal of student deals', link: 'https://www.myunidays.com/', category: 'General' },
    { id: 27, domain: 'studentbeans.com', name: 'StudentBeans', offer: 'Infinite student discounts', link: 'https://www.studentbeans.com/', category: 'General' },
    { id: 28, domain: 'shein.com', name: 'SHEIN', offer: 'Extra 15% student discount', link: 'https://www.shein.com/', category: 'Fashion', code: 'STUDENT15' },
    { id: 29, domain: 'zara.com', name: 'Zara', offer: 'Seasonal student sales', link: 'https://www.zara.com/', category: 'Fashion' },
    { id: 30, domain: 'mcdonalds.com', name: "McDonald's", offer: 'Free burger with meal', link: 'https://www.mcdonalds.com/', category: 'Food' }
];
